#!/usr/bin/env bash

set -euEo pipefail


declare SCRIPT_FILE_PATH
SCRIPT_FILE_PATH="${0}"
export SCRIPT_FILE_PATH

declare SCRIPT_FILE_NAME
SCRIPT_FILE_NAME="$( basename "${0}" )"
export SCRIPT_FILE_NAME

declare file_name
for file_name in "logging" "exit-codes" "media"; do
    source "%{INSTALL_FOLDER}/lib/encrypted-storage/functions/${file_name}"
done


trap 'log_error "Something went wrong! Quitting... "' ERR

main()
{
    log_info "Starting..."
    
    declare action
    action="${1}"
    shift 1

    case "${action}" in

        list-media | list | l )
                list_medium_names "${@}"
            ;;

        mount-medium | mount | m )
                declare mount_helper_name
                mount_helper_name=""

                declare medium_name
                medium_name=""

                declare key_file_path
                key_file_path=""

                declare -a arguments
                arguments=()

                while true; do
                    case "${1:-""}" in
                        --mount-helper | -u )
                                mount_helper_name="${2}"
                                shift 2
                            ;;

                        --mount-helper=* )
                                mount_helper_name="${1#"--mount-helper="}"
                                shift 1
                            ;;

                        --name | -n )
                                medium_name="${2}"
                                shift 2
                            ;;

                        --name=* )
                                medium_name="${1#"--name="}"
                                shift 1
                            ;;

                        --key-file | -k )
                                key_file_path="${2}"
                                shift 2
                            ;;

                        --key-file=* )
                                key_file_path="${1#"--key-file="}"
                                shift 1
                            ;;

                            
                        "" )
                                break
                            ;;

                        * )
                                arguments+=("${1}")
                                shift 1
                            ;;
                    esac
                done

                declare mount_point
                mount_point="${arguments[0]}"

                if [[ -z "${medium_name}" ]]; then
                    medium_name="$( basename "${mount_point}" )"
                fi

                if [[ -z "${key_file_path}" ]]; then
                    key_file_path="$( config_folder_path )/${medium_name}.key"
                fi

                if [[ -z "${INVOCATION_ID:-""}" ]]; then
                    echo "We are here... " >&2
                    systemd-run \
                        --setenv="CONFIG_FOLDER_PATH" \
                        --setenv="RUNTIME_FOLDER_PATH" \
                        --quiet \
                        --wait \
                        --same-dir \
                        --pty \
                        --collect \
                        --pipe \
                        --property="Type=exec" \
                        --property="LoadCredentialEncrypted=${medium_name}.key:$( realpath "${key_file_path}" )" \
                            -- \
                                "${SCRIPT_FILE_PATH}" \
                                    mount-medium \
                                        --name="${medium_name}" \
                                        --key-file='${CREDENTIALS_DIRECTORY}'"/${medium_name}.key" \
                                        $( if [[ ! -z "${mount_helper_name}" ]]; then echo "--mount-helper=${mount_helper_name}"; fi ) \
                                            "${mount_point}"
                else
                    echo "We are here! " >&2
                    mount_medium "${medium_name}" "${mount_point}" "${key_file_path}" "${mount_helper_name}"
                fi
            ;;

        unmount-medium | unmount | umount | u )
                declare medium_name
                medium_name=""

                declare -a arguments
                arguments=()

                while true; do
                    case "${1:-""}" in
                        --name | -n )
                                medium_name="${2}"
                                shift 2
                            ;;

                        --name=* )
                                medium_name="${1#"--name="}"
                                shift 1
                            ;;

                        "" )
                                break
                            ;;

                        * )
                                arguments+=("${1}")
                                shift 1
                            ;;
                    esac
                done

                declare mount_point
                mount_point="${arguments[0]}"

                if [[ -z "${medium_name}" ]]; then
                    medium_name="$( basename "${mount_point}" )"
                fi

                unmount_medium "${medium_name}" "${mount_point}" 
            ;;

        * )
            die ${EXIT_CODE_UNKNOWN_ACTION} "Unknown action! "

    esac
}


main "${@}"