#!/usr/bin/env bash

set -euEo pipefail


declare SCRIPT_FILE_PATH
SCRIPT_FILE_PATH="${0}"
export SCRIPT_FILE_PATH


main()
{
    declare key_file_path
    key_file_path="${1}"

    if [[ -z "${INVOCATION_ID:-""}" ]]; then
        systemd-run \
            --quiet \
            --wait \
            --same-dir \
            --pty \
            --collect \
            --pipe \
            --property="LoadCredentialEncrypted=key:$( realpath "${key_file_path}" )" \
                -- \
                    "${SCRIPT_FILE_PATH}" '${CREDENTIALS_DIRECTORY}/key'
    else
        echo "key_file_path=${key_file_path}" >&2
    fi
}

main "${@}"