#!/usr/bin/env bash

declare LOG_INFO
LOG_INFO="info"
export LOG_INFO


declare LOG_ERROR
LOG_ERROR="error"
export LOG_ERROR


log_info()
{
    log ${LOG_INFO} "${*}"
}


log_error()
{
    log ${LOG_ERROR} "${*}"
}


log()
{
    declare level
    level="${1}"
    shift 1

    declare context
    context="${LOG_CONTEXT:-"none"}"

    declare file_path
    file_path="${LOG_FILE_PATH:-"/dev/null"}"

    declare quiet
    quiet=${LOG_QUIET:-false}

    tee -a "${file_path}" \
        <<<"${context}/${level} ${*}" \
        >"$( 
            if ${quiet}; then 
                echo "/dev/null"
            else
                echo "/dev/stderr"
            fi 
        )"
}