#!/bin/bash 

set -euEo pipefail


main()
{
    declare normal_folder_path
    normal_folder_path="${1}"

    mkdir -p "${normal_folder_path}/sensitive-storage.target.wants"

    declare medium
    for medium in $( sensitive-storage list ); do

        declare mount_point
        mount_point="$( sensitive-storage mount-point "${medium}" )"

        declare automount_unit_file_path
        automount_unit_file_path="${normal_folder_path}/$( systemd-escape --path --suffix="automount" "${mount_point}" )"
        cat <<EOCAT >"${automount_unit_file_path}"
[Unit]
Description=${medium} Automount

[Automount]
Where=${mount_point}
TimeoutIdleSec=5

[Install]
WantedBy=sensitive-storage.target
EOCAT
        ln -s "${automount_unit_file_path}" "${normal_folder_path}/sensitive-storage.target.wants"

        declare mount_unit_file_path
        mount_unit_file_path="${normal_folder_path}/$( systemd-escape --path --suffix="mount" "${mount_point}" )"
        cat <<EOCAT >"${mount_unit_file_path}"
[Unit]
Description=${medium}

[Mount]
What=${medium}
Where=${mount_point}
Type=sensitive-storage

[Install]
WantedBy=sensitive-storage.target
EOCAT
        ln -s "${mount_unit_file_path}" "${normal_folder_path}/sensitive-storage.target.wants"

    done
}

main "${@}"